# -*- mode: python ; coding: utf-8 -*-
# TimeTrack — PyInstaller spec (--onedir, no console)
#
# Build with:  build.bat   OR   .venv\Scripts\pyinstaller.exe TimeTrack.spec
#
# Output: dist\TimeTrack\TimeTrack.exe  (self-contained directory)

from PyInstaller.utils.hooks import collect_all

# uvicorn and anyio use dynamic plugin loading — collect everything
_uvi_d, _uvi_b, _uvi_h = collect_all('uvicorn')
_any_d, _any_b, _any_h = collect_all('anyio')

block_cipher = None

a = Analysis(
    ['tray.py'],
    pathex=['.'],
    binaries=_uvi_b + _any_b,
    datas=[
        ('ui',                  'ui'),       # HTML dashboard files
        ('images/favicon_1.png','images'),   # tray/favicon assets
    ] + _uvi_d + _any_d,
    hiddenimports=_uvi_h + _any_h + [
        # pystray Windows backend
        'pystray._win32',
        # Windows registry (built-in, but explicit for frozen builds)
        'winreg',
        # pydantic v2 internals
        'pydantic',
        'pydantic_core',
        'pydantic.deprecated.class_validators',
        # win11toast (optional — app falls back gracefully if unavailable)
        'win11toast',
        # FastAPI / starlette
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        # HTTP parsers used by uvicorn
        'h11',
        'httptools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude heavy unused packages to keep the build small
        'tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy',
        'IPython', 'jupyter', 'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TimeTrack',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,          # no console window (equivalent to pythonw.exe)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='images/TimeTrack.ico',   # generated by build.bat from images/favicon_1.png
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TimeTrack',
)
