# -*- mode: python ; coding: utf-8 -*-
# TimeTrack — PyInstaller spec (--onefile, no console)
#
# Build with:  build.bat   OR   .venv\Scripts\pyinstaller.exe TimeTrack-onefile.spec
#
# Output: dist\TimeTrack.exe  (un único fichero, sin dependencias externas)
#
# Por qué existe esta variante además de TimeTrack.spec (onedir):
#   La build onedir reparte el programa entre TimeTrack.exe y la carpeta
#   _internal\. Si el usuario copia solo el .exe —el error más habitual al
#   compartirlo— el proceso arranca pero nunca levanta el servidor. Este .spec
#   empaqueta TODO dentro del ejecutable, de modo que no se puede separar.
#
# Las rutas de datos siguen funcionando igual: sys.executable apunta al .exe
# real (no al directorio temporal de extracción), así que la BD, el log y
# images\app-images se crean junto al ejecutable y persisten entre ejecuciones.

from PyInstaller.utils.hooks import collect_all

# uvicorn and anyio use dynamic plugin loading — collect everything
_uvi_d, _uvi_b, _uvi_h = collect_all('uvicorn')
_any_d, _any_b, _any_h = collect_all('anyio')

block_cipher = None

a = Analysis(
    ['tray.py'],
    pathex=['.'],
    binaries=_uvi_b + _any_b,
    datas=[
        ('ui',                  'ui'),       # HTML dashboard files
        ('images/timetrack/favicon_1.png','images/timetrack'),   # tray/favicon assets
    ] + _uvi_d + _any_d,
    hiddenimports=_uvi_h + _any_h + [
        # pystray Windows backend
        'pystray._win32',
        # Windows registry (built-in, but explicit for frozen builds)
        'winreg',
        # pydantic v2 internals
        'pydantic',
        'pydantic_core',
        'pydantic.deprecated.class_validators',
        # win11toast (optional — app falls back gracefully if unavailable)
        'win11toast',
        # FastAPI / starlette
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        # HTTP parsers used by uvicorn
        'h11',
        'httptools',
        # Subida de carátulas (FastAPI lo importa de forma diferida)
        'multipart',
        'python_multipart',
        # Backend del tray y generación de iconos
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude heavy unused packages to keep the build small
        'tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy',
        'IPython', 'jupyter', 'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# onefile: binaries, zipfiles y datas van DENTRO del EXE (sin COLLECT)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TimeTrack',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # no console window (equivalent to pythonw.exe)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='images/timetrack/TimeTrack.ico',   # generated by build.bat
)
